version: '2'
services:
    resource-app:
        image: resource
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://resource-postgresql:5432/resource
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    resource-postgresql:
        extends:
            file: postgresql.yml
            service: resource-postgresql
